var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(){var p=this,aa=function(a,b){var c=a.split("."),d=p;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b},ba=function(a,b,c){return a.call.apply(a.bind,arguments)},ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,
arguments)}},q=function(a,b,c){q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ba:ca;return q.apply(null,arguments)},da=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};var u=(new Date).getTime();var v=function(a){a=parseFloat(a);return isNaN(a)||1<a||0>a?0:a},x=function(a){return/^true$/.test(a)?!0:!1},ea=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,A=function(a,b){if(!a)return b;var c=a.match(ea);return c?c[0]:b};var fa=x("false"),ga=x("false"),ha=x("false"),ia=x("false");var C=function(a,b,c){c||(c=ia?"https":"http");return[c,"://",a,b].join("")};var ja=v("0.15"),ka=v("0"),la=v(""),ma=v("0.2");var na=function(){return A("","pagead2.googlesyndication.com")};var oa=document,D=window;var pa=/&/g,qa=/</g,ra=/>/g,sa=/\"/g,E={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"},F={"'":"\\'"};na();
var G=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(null,a[c],c,a)},H=function(a){return!!a&&"function"==typeof a&&!!a.call},ta=function(a,b){if(!(2>arguments.length))for(var c=1,d=arguments.length;c<d;++c)a.push(arguments[c])},I=function(a,b){if(!(1E-4>Math.random())){var c=Math.random();if(c<b)return a[Math.floor(c/b*a.length)]}return null},ua=function(a){a.google_unique_id?++a.google_unique_id:a.google_unique_id=1},J=function(a){try{return!!a.location.href||""===
a.location.href}catch(b){return!1}};var va={client:"google_ad_client",format:"google_ad_format",slotname:"google_ad_slot",output:"google_ad_output",ad_type:"google_ad_type"},K=function(a,b,c,d){var e=q(b,p,a);b=q(b,p,"onerror::"+a);a=window.onerror;window.onerror=b;try{c()}catch(f){c=!ha;try{var g=f.toString();f.name&&-1==g.indexOf(f.name)&&(g+=": "+f.name);f.message&&-1==g.indexOf(f.message)&&(g+=": "+f.message);if(f.stack){var l=f.stack;b=g;try{-1==l.indexOf(b)&&(l=b+"\n"+l);for(var n;l!=n;)n=l,l=l.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,
"$1");g=l.replace(/\n */g,"\n")}catch(k){g=b}}l="";f.fileName&&(l=f.fileName);n=-1;f.lineNumber&&(n=f.lineNumber);var h;t:{try{h=d?d():"";break t}catch(m){}h=""}c=e(g,l,n,h)}catch(y){wa({context:"protectAndRun",msg:y.toString()+"\n"+(y.stack||"")})}if(!c)throw f;}window.onerror=a};aa("google_protectAndRun",K);
var L=function(a,b,c,d,e){a={jscb:fa?1:0,jscd:ga?1:0,context:a,msg:b.substring(0,512),eid:e&&e.substring(0,40),file:c,line:d.toString(),url:oa.URL.substring(0,512),ref:oa.referrer.substring(0,512)};xa(a);wa(a);return!ha};aa("google_handleError",L);
var wa=function(a){if(0.01>Math.random()){a="/pagead/gen_204?id=jserror"+ya(a);a=C(A("","pagead2.googlesyndication.com"),a);a=a.substring(0,2E3);D.google_image_requests||(D.google_image_requests=[]);var b=D.document.createElement("img");b.src=a;D.google_image_requests.push(b)}},xa=function(a){var b=a||{};G(va,function(a,d){b[d]=D[a]})},M=function(a,b){return da(K,a,L,b,void 0)},ya=function(a){var b="";G(a,function(a,d){if(0===a||a)b+="&"+d+"="+("function"==typeof encodeURIComponent?
encodeURIComponent(a):escape(a))});return b};var N=null,za=function(){if(!N){for(var a=window,b=a,c=0;a!=a.parent;)if(a=a.parent,c++,J(a))b=a;else break;N=b}return N};var Aa=function(){},O=function(a,b,c){switch(typeof b){case "string":Ba(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(b instanceof Array){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),O(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)b.hasOwnProperty(e)&&(f=b[e],"function"!=typeof f&&(c.push(d),Ba(e,c),c.push(":"),O(a,f,c),d=
","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}},P={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Ca=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g,Ba=function(a,b){b.push('"');b.push(a.replace(Ca,function(a){if(a in P)return P[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return P[a]=e+b.toString(16)}));b.push('"')};var Da=function(a){a.google_page_url&&(a.google_page_url=String(a.google_page_url));var b=[];G(a,function(a,d){if(null!=a){var e;try{var f=[];O(new Aa,a,f);e=f.join("")}catch(g){}e&&ta(b,d,"=",e,";")}});return b.join("")};var Ea=/\.((google(|groups|mail|images|print))|gmail)\./,Fa=function(a){try{var b=Ea.test(a.location.host);return!(!a.postMessage||!a.localStorage||!a.JSON||b)}catch(c){return!1}};var Q=function(a){this.b=a;a.google_iframe_oncopy||(a.google_iframe_oncopy={handlers:{}});this.i=a.google_iframe_oncopy},Ga;var R="var i=this.id,s=window.google_iframe_oncopy,H=s&&s.handlers,h=H&&H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&&d&&(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){w.location.replace(h)}}";
/[&<>\"]/.test(R)&&(-1!=R.indexOf("&")&&(R=R.replace(pa,"&amp;")),-1!=R.indexOf("<")&&(R=R.replace(qa,"&lt;")),-1!=R.indexOf(">")&&(R=R.replace(ra,"&gt;")),-1!=R.indexOf('"')&&(R=R.replace(sa,"&quot;")));Ga=R;Q.prototype.set=function(a,b){this.i.handlers[a]=b;this.b.addEventListener&&!/MSIE/.test(navigator.userAgent)&&this.b.addEventListener("load",q(this.j,this,a),!1)};Q.prototype.j=function(a){a=this.b.document.getElementById(a);var b=a.contentWindow.document;if(a.onload&&b&&(!b.body||!b.body.firstChild))a.onload()};var S,T,U,V,Ha=function(){return p.navigator?p.navigator.userAgent:null};V=U=T=S=!1;var W;if(W=Ha()){var Ia=p.navigator;S=0==W.lastIndexOf("Opera",0);T=!S&&(-1!=W.indexOf("MSIE")||-1!=W.indexOf("Trident"));U=!S&&-1!=W.indexOf("WebKit");V=!S&&!U&&!T&&"Gecko"==Ia.product}var Ja=T,Ka=V,La=U;var X;if(S&&p.opera){var Ma=p.opera.version;"function"==typeof Ma&&Ma()}else Ka?X=/rv\:([^\);]+)(\)|;)/:Ja?X=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:La&&(X=/WebKit\/(\S+)/),X&&X.exec(Ha());var Y,Z=function(a){this.c=[];this.b=a||window;this.a=0;this.d=null},Na=function(a,b){this.k=a;this.h=b};Z.prototype.m=function(a,b){0!=this.a||0!=this.c.length||b&&b!=window?this.g(a,b):(this.a=2,this.f(new Na(a,window)))};Z.prototype.g=function(a,b){this.c.push(new Na(a,b||this.b));Oa(this)};Z.prototype.n=function(a){this.a=1;if(a){var b=M("sjr::timeout",q(this.e,this));this.d=this.b.setTimeout(b,a)}};
Z.prototype.e=function(){1==this.a&&(null!=this.d&&(this.b.clearTimeout(this.d),this.d=null),this.a=0);Oa(this)};Z.prototype.o=function(){return!0};Z.prototype.nq=Z.prototype.m;Z.prototype.nqa=Z.prototype.g;Z.prototype.al=Z.prototype.n;Z.prototype.rl=Z.prototype.e;Z.prototype.sz=Z.prototype.o;var Oa=function(a){var b=M("sjr::tryrun",q(a.l,a));a.b.setTimeout(b,0)};
Z.prototype.l=function(){if(0==this.a&&this.c.length){var a=this.c.shift();this.a=2;var b=M("sjr::run",q(this.f,this,a));a.h.setTimeout(b,0);Oa(this)}};Z.prototype.f=function(a){this.a=0;a.k()};
var Pa=function(a){try{return a.sz()}catch(b){return!1}},Qa=function(a){return!!a&&("object"==typeof a||"function"==typeof a)&&Pa(a)&&H(a.nq)&&H(a.nqa)&&H(a.al)&&H(a.rl)},Ra=function(){if(Y&&Pa(Y))return Y;var a=za(),b=a.google_jobrunner;return Qa(b)?Y=b:a.google_jobrunner=Y=new Z(a)},Sa=function(a,b){Ra().nq(a,b)},Ta=function(a,b){Ra().nqa(a,b)};var Ua={"120x90":!0,"160x90":!0,"180x90":!0,"200x90":!0,"468x15":!0,"728x15":!0},Va=function(){var a="script";return["<",a,' src="',C(na(),"/pagead/js/r20130820/r20130206/show_ads_impl.js",""),'"></',a,">"].join("")},Wa=function(a,b,c,d){return function(){var e=!1;d&&Ra().al(3E4);try{if(J(a.document.getElementById(b).contentWindow)){var f=a.document.getElementById(b).contentWindow,
g=f.document;g.body&&g.body.firstChild||(g.open(),f.google_async_iframe_close=!0,g.write(c))}else{var l=a.document.getElementById(b).contentWindow,n;f=c;f=String(f);if(f.quote)n=f.quote();else{for(var g=['"'],k=0;k<f.length;k++){var h=f.charAt(k),m=h.charCodeAt(0),y=g,B=k+1,w;if(!(w=E[h])){var r;if(31<m&&127>m)r=h;else{var t=h;if(t in F)r=F[t];else if(t in E)r=F[t]=E[t];else{var s=t,z=t.charCodeAt(0);if(31<z&&127>z)s=t;else{if(256>z){if(s="\\x",16>z||256<z)s+="0"}else s="\\u",4096>z&&(s+="0");s+=
z.toString(16).toUpperCase()}r=F[t]=s}}w=r}y[B]=w}g.push('"');n=g.join("")}l.location.replace("javascript:"+n)}e=!0}catch(ib){l=za().google_jobrunner,Qa(l)&&l.rl()}e&&(new Q(a)).set(b,Wa(a,b,c,!1))}},Xa=function(a){var b=["<iframe"];G(a,function(a,d){b.push(" "+d+'="'+(null==a?"":a)+'"')});b.push("></iframe>");return b.join("")},Ya=function(a,b,c,d){d=d?'"':"";var e=d+"0"+d;a.width=d+b+d;a.height=d+c+d;a.frameborder=e;a.marginwidth=e;a.marginheight=e;a.vspace=e;a.hspace=e;a.allowtransparency=d+"true"+
d;a.scrolling=d+"no"+d},$a=function(a,b,c){Za(a,b,c,function(a,b,f){for(var g=b.id,l=0;!g||a.document.getElementById(g);)g="aswift_"+l++;b.id=g;b.name=g;a=Number(f.google_ad_width);g=Number(f.google_ad_height);f=["<iframe"];for(var n in b)b.hasOwnProperty(n)&&ta(f,n+"="+b[n]);f.push('style="left:0;position:absolute;top:0;"');f.push("></iframe>");n="border:none;height:"+g+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+a+"px";c.innerHTML=['<ins style="display:inline-table;',n,'"><ins id="',
b.id+"_anchor",'" style="display:block;',n,'">',f.join(" "),"</ins></ins>"].join("");return b.id})},Za=function(a,b,c,d){var e="script",f=b.google_ad_width,g=b.google_ad_height,l={};Ya(l,f,g,!0);l.onload='"'+Ga+'"';d=d(a,l,b);var l=Da(b),n;n=window.google_override_format||!Ua[window.google_ad_width+"x"+window.google_ad_height]&&"aa"==window.google_loader_used?I(["c","e"],ma):null;var k=b.google_ad_output,h=b.google_ad_format;h||"html"!=k&&null!=k||(h=b.google_ad_width+"x"+b.google_ad_height,"e"==
n&&(h+="_as"));k=!b.google_ad_slot||b.google_override_format||!Ua[b.google_ad_width+"x"+b.google_ad_height]&&"aa"==b.google_loader_used;h=h&&k?h.toLowerCase():"";b.google_ad_format=h;h=b||D;h=[h.google_ad_slot,h.google_ad_format,h.google_ad_type,h.google_ad_width,h.google_ad_height];if(c){if(c){for(var k=[],m=0;c&&25>m;c=c.parentNode,++m)k.push(9!=c.nodeType&&c.id||"");c=k.join()}else c="";c&&h.push(c)}c=0;if(h)if(c=h.join(":"),h=c.length,0==h)c=0;else{k=305419896;for(m=0;m<h;m++)k^=(k<<5)+(k>>2)+
c.charCodeAt(m)&4294967295;c=0<k?k:4294967296+k}c=c.toString();h=Fa(a);k=3==({visible:1,hidden:2,prerender:3,preview:4}[a.document.webkitVisibilityState||a.document.mozVisibilityState||a.document.visibilityState||""]||0);h&&(!k&&void 0===a.google_ad_handling_mode)&&(a.google_ad_handling_mode=I(["XN","AZ"],ka)||I(["EI"],la));h=a.google_ad_handling_mode?String(a.google_ad_handling_mode):null;if(Fa(a)&&1==a.google_unique_id&&"XN"!=h){k="zrt_ads_frame"+a.google_unique_id;b=b.google_page_url;if(!b){n:{b=
a.document;var m=f||a.google_ad_width,y=g||a.google_ad_height;if(a.top==a)b=!1;else{var B=b.documentElement;if(m&&y){var w=1,r=1;a.innerHeight?(w=a.innerWidth,r=a.innerHeight):B&&B.clientHeight?(w=B.clientWidth,r=B.clientHeight):b.body&&(w=b.body.clientWidth,r=b.body.clientHeight);if(r>2*y||w>2*m){b=!1;break n}}b=!0}}b=b?a.document.referrer:a.document.URL}b=encodeURIComponent(b);m=null;if("PC"==h||"EI"==h||"AZ"==h){switch(h){case "EI":m="I";break;case "AZ":m="Z";break;default:m="K"}m=m+"-"+(b+"/"+
c+"/"+a.google_unique_id)}b={};Ya(b,f,g,!1);b.style="display:none";f=m;b.id=k;b.name=k;b.src=C(A("","googleads.g.doubleclick.net"),["/pagead/html/r20130820/r20130206/zrt_lookup.html",f?"#"+encodeURIComponent(f):""].join(""));f=Xa(b)}else f=null;g=(new Date).getTime();b=a.google_top_experiment;k=a.google_async_for_oa_experiment;m=a.google_always_use_delayed_impressions_experiment;l=["<!doctype html><html><body>",
f,"<",e,">",l,"google_show_ads_impl=true;google_unique_id=",a.google_unique_id,';google_async_iframe_id="',d,'";google_ad_unit_key="',c,'";google_start_time=',u,";",b?'google_top_experiment="'+b+'";':"",h?'google_ad_handling_mode="'+h+'";':"",k?'google_async_for_oa_experiment="'+k+'";':"",m?'google_always_use_delayed_impressions_experiment="'+m+'";':"",n?'google_append_as_for_format_override="'+n+'";':"","google_bpp=",g>u?g-u:1,";</",e,">",Va(),"</body></html>"].join("");(a.document.getElementById(d)?
Sa:Ta)(Wa(a,d,l,!0))},ab=function(a,b){for(var c=a.attributes,d=c.length,e=0;e<d;e++){var f=c[e];if(/data-/.test(f.nodeName)){var g=f.nodeName.replace("data","google").replace(/-/g,"_");b.hasOwnProperty(g)||(b[g]=f.nodeValue)}}c=/([0-9.]+)px/;c.test(a.style.width)&&c.test(a.style.height)||(e=window.getComputedStyle?window.getComputedStyle(a,null):a.currentStyle,a.style.width=e.width,a.style.height=e.height);d=["width","height"];for(e=0;e<d.length;e++)g="google_ad_"+d[e],b.hasOwnProperty(g)||(f=c.exec(a.style[d[e]]))&&
(b[g]=Math.round(f[1]))},bb=Math.floor(1E6*Math.random()),cb=function(a){for(var b=a.data.split("\n"),c={},d=0;d<b.length;d++){var e=b[d].indexOf("=");-1!=e&&(c[b[d].substr(0,e)]=b[d].substr(e+1))}b=c[3];if(c[1]==bb&&(window.google_top_js_status=4,a.source==top&&0==b.indexOf(a.origin)&&(window.google_top_values=c,window.google_top_js_status=5),window.google_top_js_callbacks)){for(a=0;a<window.google_top_js_callbacks.length;a++)window.google_top_js_callbacks[a]();window.google_top_js_callbacks.length=
0}};var $=["google_analytics_uacct","google_analytics_domain_name"],db=function(a){return/(^| )adsbygoogle($| )/.test(a.className)&&"done"!=a.getAttribute("data-adsbygoogle-status")},eb=function(a,b,c){ua(c);ab(a,b);for(var d=0;d<$.length;d++)b[$[d]]=b[$[d]]||c[$[d]];b.google_loader_used="aa";if((d=b.google_ad_output)&&"html"!=d)throw Error("No support for google_ad_output="+d);K("aa::main",L,function(){$a(c,b,a)})},fb=function(a){for(var b=document.getElementsByTagName("ins"),c=0,d=b[c];c<b.length;d=
b[++c])if(db(d)&&(!a||d.id==a))return d;return null},gb=function(a){var b=a.element;a=a.params||{};if(b){if(!db(b)&&(b=b.id&&fb(b.id),!b))throw Error("adsbygoogle: 'element' has already been filled.");if(!("innerHTML"in b))throw Error("adsbygoogle.push(): 'element' is not a good DOM element.");}else if(b=fb(),!b)throw Error("adsbygoogle.push(): All ins elements in the DOM with class=adsbygoogle already have ads in them.");var c=window;b.setAttribute("data-adsbygoogle-status","done");eb(b,a,c)},hb=
function(){if(!window.google_top_experiment&&!window.google_top_js_status){var a=window;if(2!==(a.top==a?0:J(a.top)?1:2))window.google_top_js_status=0;else if(top.postMessage){var b;try{b=D.top.frames.google_top_static_frame?!0:!1}catch(c){b=!1}if(b){if(window.google_top_experiment=I(["jp_c","jp_zl","jp_wfpmr"],ja),"jp_c"!==window.google_top_experiment){a=window;a.addEventListener?a.addEventListener("message",cb,!1):a.attachEvent&&a.attachEvent("onmessage",cb);window.google_top_js_status=3;a={0:"google_loc_request",
1:bb};b=[];for(var d in a)b.push(d+"="+a[d]);top.postMessage(b.join("\n"),"*")}}else window.google_top_js_status=2}else window.google_top_js_status=1}if((d=window.adsbygoogle)&&d.shift)for(b=20;(a=d.shift())&&0<b--;)try{gb(a)}catch(e){throw window.setTimeout(hb,0),e;}window.adsbygoogle={push:gb}};hb();})();


}
/*
     FILE ARCHIVED ON 13:49:14 Aug 25, 2013 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 20:10:14 May 02, 2025.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 0.583
  exclusion.robots: 0.044
  exclusion.robots.policy: 0.034
  esindex: 0.01
  cdx.remote: 123.912
  LoadShardBlock: 465.845 (6)
  PetaboxLoader3.datanode: 361.47 (7)
  load_resource: 340.155
  PetaboxLoader3.resolve: 299.395
*/